#!/usr/bin/env python3
"""Filter a TGF graph generated by includegraph.py."""
import argparse
import collections
import logging
import pathlib
import sys
from typing import Any, Dict, Iterable, Set, TextIO

# Assumes that includegraph.py is a sibling of this script.
repo_root = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(repo_root))
try:
    from includegraph import (
        FileAttributes,
        GraphFormatter,
        GraphNode,
        HeaderGraph,
        SimpleTgfGraphFormatter,
    )
except ImportError:
    logging.critical("Failed to import types from includegraph.py")
    raise

LOG_LEVELS = {
    "CRITICAL": logging.CRITICAL,
    "ERROR": logging.ERROR,
    "WARNING": logging.WARNING,
    "INFO": logging.INFO,
    "DEBUG": logging.DEBUG,
}
DEFAULT_LEVEL = "INFO"


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--input",
        "-i",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="The path to the input graph. Defaults to stdin.",
    )
    # parser.add_argument(
    #     "--input-format",
    #     "-I",
    #     default="tgf",
    #     choices=["tgf"],
    #     help="The input graph format",
    # )
    parser.add_argument(
        "--output",
        "-o",
        type=argparse.FileType("w"),
        default=sys.stdout,
        help="The file to save the output to. Defaults to stdout.",
    )
    parser.add_argument(
        "--output-format",
        "-O",
        type=str,
        default="tgf",
        choices=["graphviz", "tree", "tgf"],
        help="The output format for the parsed header dependency graph. Defaults to TGF.",
    )
    parser.add_argument(
        "--system-headers",
        type=str,
        default="first",
        choices=["none", "first", "all"],
        help="How to display system headers."
        " 'none' strips out system headers."
        " 'first' strips out system headers included by other system headers."
        " 'all' shows them all.",
    )
    parser.add_argument(
        "--full-tree",
        action="store_true",
        default=False,
        help="Show the full tree, (as if there were no header guards).",
    )
    parser.add_argument(
        "--subtree",
        type=str,
        default=None,
        help="Filter the graph to just the dependencies for the given node.",
    )
    parser.add_argument(
        "--filter",
        action="append",
        help="Strip the given filepath glob from the graph.",
    )
    parser.add_argument(
        "--include-compilation-failures",
        action="store_true",
        default=False,
        help="Keep nodes that failed to compile. Otherwise, nodes the failed to compile, along"
        " with any dependents will be stripped.",
    )
    parser.add_argument(
        "--log-level",
        "-l",
        type=str,
        default=DEFAULT_LEVEL,
        choices=LOG_LEVELS.keys(),
        help=f"Set the logging output level. Defaults to {DEFAULT_LEVEL}.",
    )
    return parser.parse_args()


def parse_tgf_graph(input: TextIO) -> HeaderGraph:
    """Parse graph in TGF format.

    Nodes include metadata as specified by GraphNode and FileAttributes, and as serialized by
    includegraph.py:output_dep_graph_tgf()

    Example:
        "examples/example1/src/example1.cpp"    FileAttributes(is_system_header=False, is_top_level_system_header=False, compile_failed=False)
        "examples/example1/src/private.h"       FileAttributes(is_system_header=False, is_top_level_system_header=False, compile_failed=False)
        #
        "examples/example1/src/example1.cpp"    "examples/example1/src/private.h"
        "examples/example1/src/example1.cpp"    "examples/example1/include/example1/foo.h"
        "examples/example1/src/private.h"       "examples/example1/src/circular.h"
    """
    lines = iter(input.readlines())

    # Have to defer until the edge parsing to construct the GraphNodes
    graph = collections.defaultdict(set)

    # filename -> FileAttributes
    attributes = {}
    filenames = set()

    # Read the node list until the '#'
    for line in lines:
        line = line.strip()

        # '#' sentinel marks the end of the node list
        if line.startswith("#"):
            break

        filename, *file_attributes = line.split()
        filename = filename.strip("'\"")
        filenames.add(filename)
        file_attributes = " ".join(file_attributes)
        file_attributes = file_attributes.strip("'\"")
        if file_attributes and file_attributes.startswith("FileAttributes("):
            try:
                # Arbitrary code execution isn't ideal. But fine for a prototype? It's structured
                # enough that we could parse the hard way if we wanted.
                file_attributes = eval(file_attributes, {}, {"FileAttributes": FileAttributes})
                attributes[filename] = file_attributes
                logging.debug(
                    "Parsed attributes for filename: '%s' -> '%s'", filename, file_attributes
                )
            except BaseException as e:
                logging.error(
                    "Failed to parse attributes '%s' as FileAttributes", file_attributes, exc_info=e
                )
                continue
        else:
            logging.warning(
                "Line '%s' doesn't look like a FileAttributes namedtuple. Cowardly refusing to parse.",
                line,
            )
            continue
        source_attributes = attributes.get(filename, None)
        source_node = GraphNode(filename=filename, attributes=source_attributes)
        graph[source_node] = set()

    logging.info("Parsed %d nodes", len(filenames))

    # Read the edge list until the end
    for line in lines:
        line = line.strip()
        source, target = None, None
        try:
            source, target, *label = line.split()
            source = source.strip("'\"")
            target = target.strip("'\"")
            label = " ".join(label)
        except BaseException as e:
            logging.error("Failed to parse edge from '%s'", line, exc_info=e)
            continue

        if source not in filenames or target not in filenames:
            logging.error(
                "Edge '%s' -> '%s' contains a node not found in node list", source, target
            )
            continue
        source_attributes = attributes.get(source, None)
        source_node = GraphNode(filename=source, attributes=source_attributes)
        target_attributes = attributes.get(target, None)
        target_node = GraphNode(filename=target, attributes=target_attributes)
        graph[source_node].add(target_node)

    return graph


def topological_sort(graph: Dict[Any, Iterable[Any]]) -> Iterable[Any]:
    """Topologically sort the keys of a graph."""
    sorted_keys = []
    seen = set()

    def recursive_helper(node: str):
        for neighbor in graph.get(node, []):
            if neighbor not in seen:
                seen.add(neighbor)
                recursive_helper(neighbor)
        if node not in sorted_keys:
            sorted_keys.append(node)

    for key in graph.keys():
        recursive_helper(key)
    return sorted_keys


# TODO: This no longer works because of how nodes are added to the graph in includegraph.py
# TODO: Further, this only works right if there's one translation unit. (the first topologically
# sorted key, the rest of the top-level dependents will be missed)
def output_graph_tree(graph: HeaderGraph, output: TextIO):
    """Output the include graph as a tree.

    Example:
        example1.cpp
            foo.h
            bar.h
            private.h
                circular.h

    Each level of indentation will be a single tab character.
    """

    def recursive_dfs_helper(graph: HeaderGraph, source: GraphNode, depth: int, path=[]):
        indent = "\t" * depth
        print(f"{indent}{source.filename}", file=output)
        if source not in path:
            path.append(source)
            if source not in graph:
                return path
            for neighbor in graph[source]:
                path = recursive_dfs_helper(graph, neighbor, depth + 1, path)
        return path

    # Don't crash on an empty graph
    if not graph:
        return

    # Get a top-level candidate (is not depended on by anything else) to print first at depth=0
    sorted_keys = topological_sort(graph)
    root = sorted_keys[-1]

    recursive_dfs_helper(graph, root, depth=0)


class SimpleTreeFormatter(GraphFormatter):
    def format(self, graph: HeaderGraph, output: TextIO):
        output_graph_tree(graph, output)


class SimpleGraphvizFormatter(GraphFormatter):
    def start_node_list(self, graph: HeaderGraph, output: TextIO):
        print("digraph header_graph {", file=output)

    def visit_edge(self, source: GraphNode, target: GraphNode, output: TextIO):
        print(f'\t"{source.filename}" -> "{target.filename}";', file=output)

    def finish_edge_list(self, graph: HeaderGraph, output: TextIO):
        print("}", file=output)


def output_graph(graph: HeaderGraph, output: TextIO, format: str):
    formatter = None
    if format == "tgf":
        formatter = SimpleTgfGraphFormatter()
    elif format == "tree":
        formatter = SimpleTreeFormatter()
    elif format == "graphviz":
        formatter = SimpleGraphvizFormatter()
    else:
        sys.exit(1)
    formatter.format(graph, output)


def main(args):
    graph = parse_tgf_graph(args.input)

    # TODO: There's all sorts of styling configuration to pass!
    # TODO: I think this makes sense to do with a visitor pattern (visit all the nodes, and then
    # visit all the edges)
    output_graph(graph, args.output, args.output_format)


if __name__ == "__main__":
    args = parse_args()
    logging.basicConfig(
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        level=LOG_LEVELS.get(args.log_level),
        stream=sys.stderr,
    )
    main(args)
